version: '{build}'
image: Visual Studio 2017
install:
  # latest NodeJS version
  - ps: Install-Product node ''
  - npm install -g gulp
  - npm install
build_script:
  - node --version
  - npm --version
  - gulp --mode Release
test: off
